# fly.toml app configuration file generated for family-pods on 2023-09-17T23:05:07+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "family-pods"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
